Stackless issue #290: bpo-36974, PEP 590 Vectorcall-protocol
stackless-dev/stackless pull request #291
Opened 2021-07-27 13:00 UTC by akruis

Support the Vectorcall protocol in Stackless.

2021-07-31 17:04 UTC, akruis commented
This pull request currently blocks any development, because branch "main-slp" does not compile. I'm now fairly confident that the code change is OK. But the documentation update needs to be reviewed. Therefore I'll split this pull request into two requests: a new one for the code change and this one for the documentation.

2021-08-03 13:58 UTC, kristjanvalur requested changes
The salient point seems to be the additional possible value beside 0 and 1, of the callable address.

Can you explain how the new protocol (with the function address) works?  Could that solution be used for all functions, instead of the old one having a flag in the type?

2021-08-03 13:58 UTC, kristjanvalur commented on Doc/c-api/stackless.rst
> +Within the body of a soft-switchable extension function (or any other C-function, that obyes the stackless-protocol)
"obeys"

2021-08-03 13:58 UTC, kristjanvalur commented on Include/stackless_api.h
> +  cases where we know that the called function will take care of our object,
"take care of our object", is confusing.  maybe fix this to say "obeys the stackless protocol by checking the `_PyStackless_TRY_STACKLESS` function and possibly returning the unwind token.  (unless I misunderstand)

2021-08-03 13:58 UTC, kristjanvalur commented on Include/internal/pycore_slp_pystate.h
> +     *
This is the salient change, right? the *other* value?  Maybe it should be documented here why
 - it is necessary (something about vectorcall functions being properties)
 - how it works, in particular, how we can do it without knowing if the called function supports the protocol or not.

2021-08-04 17:18 UTC, akruis commented
> The salient point seems to be the additional possible value beside 0 and 1, of the callable address.

Indeed.

> Can you explain how the new protocol (with the function address) works?

See the new comment in pycore_slp_pystate.h. It is an implementation detail, which is why I didn't describe it in the API documentation.

> Could that solution be used for all functions, instead of the old one having a flag in the type?

In theory, but it would probably hurt efficiency.  function, that only wraps
another stackless-aware function, does not need to use STACKLESS_GETARG(),
STACKLESS_PROMOTE_xxx and STACKLESS_ASSERT(). Also some stackless-aware functions
are `static inline` and have no address.

2021-08-05 09:30 UTC, kristjanvalur approved these changes
Great stuff.
I realize that this is API documentation.  But isn't there some general `implementation` documentation too, somewhere?  Something that doesn't require browsing .h and .c files and gives a broader overview?  I suppose that could be a good home for certain implementation details, like the mechanics of soft and hard switching.

2021-08-05 09:55 UTC, akruis commented
> Great stuff.

Oh, thanks.

> I realize that this is API documentation. But isn't there some general `implementation` documentation too, somewhere? 
Something that doesn't require browsing .h and .c files and gives a broader overview?

That's a real issue, I'm not aware of any current 'implementation' documentation. Even worse, there is still some documentation around from times, when Stackless was really stackless. Nowadays it uses stack spilling.

Eventually Christian Tismer has some documentation.

> I suppose that could be a good home for certain implementation details, like the mechanics of soft and hard switching.

Sure.

2021-08-05 12:25 UTC, merged